// Test vectors generated by the Python server (api/crypto.py) with a fixed IV.
// See ios-6/tools/crypto_test_vector.py for the reproduction recipe.

#import "CryptoParityTest.h"
#import "Crypto.h"

static NSString *Hex(NSData *data) {
    NSMutableString *s = [NSMutableString stringWithCapacity:data.length * 2];
    const uint8_t *b = data.bytes;
    for (NSUInteger i = 0; i < data.length; i++) [s appendFormat:@"%02x", b[i]];
    return s;
}

@implementation CryptoParityTest

+ (BOOL)runWithLogging {
    BOOL ok = YES;

    NSString *expectedKeyHex = @"b602babf64d45c5d07e1f5b1a82f6aca4363cabad74b63c4a0a1ce4ee59a4f97";
    NSString *expectedToken  = @"dd8bee6ab4376ec7825f20c15048d4edc757fd6a883c3f8e24249f525cd468ee";

    NSData *key = [Crypto deriveKeyFromPassword:@"test123"];
    NSString *gotKeyHex = Hex(key);
    if (![gotKeyHex isEqualToString:expectedKeyHex]) {
        NSLog(@"[CryptoParityTest] FAIL: key mismatch\n  expected %@\n  got      %@", expectedKeyHex, gotKeyHex);
        ok = NO;
    }

    NSString *gotToken = [Crypto tokenFromKey:key];
    if (![gotToken isEqualToString:expectedToken]) {
        NSLog(@"[CryptoParityTest] FAIL: token mismatch\n  expected %@\n  got      %@", expectedToken, gotToken);
        ok = NO;
    }

    NSDictionary *envelope = @{ @"iv":   @"AQIDBAUGBwgJCgsMDQ4PEA==",
                                @"data": @"Oz979NkCx/dUEzTkkbMSQBZveI7kkUaK0U5r4VG9z4g=" };
    NSError *err = nil;
    id decrypted = [Crypto decryptEnvelope:envelope withKey:key error:&err];
    if (![decrypted isKindOfClass:[NSDictionary class]]) {
        NSLog(@"[CryptoParityTest] FAIL: decrypted is not a dict: %@ (err=%@)", decrypted, err);
        ok = NO;
    } else {
        NSDictionary *d = (NSDictionary *)decrypted;
        if (![d[@"hello"] isEqual:@"world"] || ![d[@"n"] isEqual:@42]) {
            NSLog(@"[CryptoParityTest] FAIL: decrypted payload mismatch: %@", d);
            ok = NO;
        }
    }

    if (ok) NSLog(@"[CryptoParityTest] PASS: PBKDF2, SHA-256 token, and AES-256-CBC decrypt all match Python server.");
    return ok;
}

@end
