// CryptoParityTest — runs at app launch (debug only) to verify the Obj-C
// crypto matches the Python server's api/crypto.py implementation.
//
// Hardcodes test vectors generated by tools/crypto_test_vector.py.
//
// Returns YES if all parity checks pass; logs failures via NSLog otherwise.

@interface CryptoParityTest : NSObject
+ (BOOL)runWithLogging;
@end
